const pages={
 dashboard:{title:'Dashboard',html:`<div class="hero"><h2>Caya Asset Integrity Management Platform</h2><p>Controlled engineering workspace based on CSAS Version 1.0. The MVP is being built incrementally around a complete, traceable asset-integrity engineering loop.</p><div class="hero-meta"><span class="chip">CSAS v1.0</span><span class="chip">MVP Phase 1</span><span class="chip">Engineering-first architecture</span></div></div><div class="cards"><div class="card"><div class="label">Equipment</div><div class="value">0</div><div class="sub">Physical assets</div></div><div class="card"><div class="label">RBI Assessments</div><div class="value">0</div><div class="sub">Controlled revisions</div></div><div class="card"><div class="label">Open Triggers</div><div class="value">0</div><div class="sub">Engineering review</div></div><div class="card"><div class="label">Pending Approval</div><div class="value">0</div><div class="sub">Workflow queue</div></div></div><div class="section"><h3>Core Engineering Loop</h3><div class="workflow-line"><span class="workflow-step">Equipment</span><span class="workflow-step">Inspection</span><span class="workflow-step">Corrosion</span><span class="workflow-step">RBI</span><span class="workflow-step">Strategy</span><span class="workflow-step">Review</span><span class="workflow-step">Approval</span></div></div><div class="section"><h3>Platform Modules</h3><div class="module-grid">${moduleCards}</div></div>`},
 equipment:{title:'Equipment',desc:'Primary physical asset records. Equipment is the main physical asset object in Caya; components remain subordinate objects and are not primary risk units in the current architecture.',html:`
<div class="page-panel equipment-page">
  <div class="equipment-header"><div><h2>Equipment</h2><p class="placeholder">Primary physical asset records and controlled engineering data.</p></div><button class="primary-btn" id="add-equipment">+ Add Equipment</button></div>
  <div class="equipment-toolbar"><input id="equipment-search" class="search-input" type="search" placeholder="Search equipment by tag, name or service..."><select id="equipment-type-filter" class="filter-select"><option value="">All Types</option><option>Pressure Vessel</option><option>Heat Exchanger</option><option>Column / Tower</option><option>Reactor</option><option>Storage Tank</option><option>Piping</option><option>Boiler</option><option>Furnace</option></select><select id="equipment-status-filter" class="filter-select"><option value="">All Statuses</option><option>In Service</option><option>Out of Service</option><option>Under Maintenance</option><option>Retired</option></select></div>
  <div id="equipment-list"></div>
</div>`},
 components:{title:'Components',desc:'Subordinate equipment components such as shell, heads, nozzles, tube bundles and tubesheets. Components are not primary risk units in the current architecture.'},
 services:{title:'Services & Fluids',desc:'Controlled service and fluid definitions used by Equipment, Corrosion, RBI, IOW and other engineering domains.'},
 materials:{title:'Materials',desc:'Controlled and versioned material definitions and associations for equipment and components.'},
 damage:{title:'Damage Mechanisms',desc:'Controlled damage-mechanism knowledge. API RP 571 is the principal initial reference; company and practical references are supported.',sections:['Mechanism Library','Applicability Conditions','Equipment / Material / Service','Engineering Basis','References','Knowledge Review']},
 methods:{title:'Inspection Methods',desc:'Controlled inspection-method definitions, applicability, coverage and effectiveness information used by Inspection and RBI.'},
 references:{title:'Engineering References',desc:'Controlled standards, procedures, specifications, technical papers, manufacturer references and company engineering practices.'},
 inspection:{title:'Inspection',desc:'Inspection requirements, plans, tasks, execution, locations, TML/CML, measurements, NDT results, findings, evidence and achieved effectiveness.',sections:['Inspection Requirements','Inspection Plans','Tasks & Scheduling','Execution & Coverage','Thickness / NDT Results','Findings & Evidence','Strategy Deviations','Inspection-to-RBI Triggers']},
 corrosion:{title:'Corrosion',desc:'Corrosion and degradation assessment. Corrosion calculations are owned here; corrosion rate does not independently determine the RBI interval.',sections:['Corrosion Assessments','Damage Mechanisms','Thickness History','Corrosion Rate','Degradation / Trend','Remaining Thickness & Life','Uncertainty & Assumptions','RBI / FFS Triggers']},
 rbi:{title:'RBI',desc:'Risk-Based Inspection engineering assessment: PoF, CoF, risk, risk drivers, risk target, required inspection effectiveness, inspection strategy and interval.',sections:['RBI Assessments','Damage Mechanisms','PoF','CoF','Risk Result','Risk Drivers','Risk Target','Inspection Effectiveness','Inspection Strategy','Reassessment']},
 ffs:{title:'FFS',desc:'Fitness-for-Service screening and assessment based on controlled API 579-1 / ASME FFS-1 methodologies.',sections:['FFS Screening','Assessment','Damage / Flaw Characterization','Level 1 / 2 / 3','Acceptance Evaluation','Remaining Life','Restrictions & Monitoring','Engineering Decision']},
 iow:{title:'IOW',desc:'Integrity Operating Windows and operating-event evaluation. IOW boundaries and actual operating observations remain separate controlled objects.',sections:['Operating Events','Operating Conditions','Operating States','IOW Definitions','IOW Revisions','IOW Evaluation','Exceedance','Duration / Frequency / Exposure','Engineering Triggers']},
 calculation:{title:'Calculation',desc:'Shared controlled calculation infrastructure for RBI, Corrosion, FFS and IOW evaluation. Calculation Result is distinct from Engineering Interpretation and Decision.',sections:['Methodologies','Calculation Definitions','Rules','Input Validation','Unit Conversion','Calculation Runs','Results & Intermediates','Output Validation','Assumptions / Overrides','Reproducibility','Regression Tests']},
 workflow:{title:'Workflow',desc:'Process execution around engineering assessment, interpretation, decision, technical review, approval, action, verification and closure.',sections:['Workflow Definitions','Instances','Assignments','Engineering Decision','Technical Review','Approval','Actions','Verification','Escalation','Audit']},
 documents:{title:'Documents',desc:'Controlled technical documents, evidence, engineering references and technical knowledge governance. Documents do not silently become engineering data.',sections:['Documents','Revisions','Evidence','References','Knowledge Objects','Review & Approval','Access & Retention','Search / Retrieval']},
 administration:{title:'Administration',desc:'System governance including users, roles, permissions, organizations, tenant boundaries, configuration, security and audit.',sections:['Users','Roles & Permissions','Organizations / Tenants','Access Scope','Configuration','Security','Audit','System Governance']}
};
const moduleOrder=[['equipment','Equipment','Physical asset identity, hierarchy and engineering data.'],['components','Components','Subordinate equipment components.'],['services','Services & Fluids','Controlled service and fluid master data.'],['materials','Materials','Controlled material definitions.'],['damage','Damage Mechanisms','API 571-based controlled mechanism knowledge.'],['methods','Inspection Methods','Inspection methods and effectiveness.'],['references','Engineering References','Standards and technical references.'],['inspection','Inspection','Execution, evidence and findings.'],['corrosion','Corrosion','Degradation assessment and corrosion calculations.'],['rbi','RBI','Risk assessment and inspection strategy.'],['ffs','FFS','Fitness-for-Service assessment.'],['iow','IOW','Integrity Operating Windows and events.'],['calculation','Calculation','Controlled engineering calculations.'],['workflow','Workflow','Review, decision and approval process.'],['documents','Documents','Technical documents and knowledge governance.'],['administration','Administration','Users, access and system governance.']];
const moduleCards=moduleOrder.map(([id,name,desc])=>`<div class="module" data-page="${id}"><span class="module-code">${id.toUpperCase()}</span><strong>${name}</strong><span>${desc}</span></div>`).join('');
const content=document.getElementById('page-content');const title=document.getElementById('page-title');
function render(page){const p=pages[page]||pages.dashboard;title.textContent=p.title;let html=p.html;if(!html){html=`<div class="page-panel"><h2>${p.title}</h2><p class="placeholder">${p.desc}</p>${p.sections?`<div class="module-list">${p.sections.map((s,i)=>`<div class="module-row"><strong>${String(i+1).padStart(2,'0')} &nbsp; ${s}</strong><div>Architecture-ready module area • controlled implementation</div></div>`).join('')}</div>`:`<div class="section"><div class="empty-state">No records yet. This module is structurally defined and ready for implementation.</div></div>`}</div>`}content.innerHTML=html;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>render(x.dataset.page));window.location.hash=page}

const defaultEquipment=[{tag:'42-V-30001',name:'Quench Water Tower',type:'Column / Tower',service:'Quench Water',unit:'LDPE',status:'In Service',area:'',revision:'01'}];
function getEquipment(){try{const saved=JSON.parse(localStorage.getItem('caya-equipment'));return Array.isArray(saved)&&saved.length?saved:defaultEquipment}catch(e){return defaultEquipment}}
function saveEquipment(items){localStorage.setItem('caya-equipment',JSON.stringify(items))}
function equipmentForm(){content.innerHTML=`
<div class="page-panel equipment-form">
  <div class="form-header"><div><h2>Add Equipment</h2><p class="placeholder">Create the primary equipment record. Required fields are marked with *.</p></div><button class="secondary-btn" id="cancel-equipment">Cancel</button></div>
  <div class="form-section"><h3>01 — Identification</h3><div class="form-grid">
    <label>Equipment Tag *<input id="eq-tag" required placeholder="e.g. 42-V-30001"></label>
    <label>Equipment Name<input id="eq-name" placeholder="e.g. Quench Water Tower"></label>
    <label>Equipment Type *<select id="eq-type"><option value="">Select type</option><option>Pressure Vessel</option><option>Heat Exchanger</option><option>Column / Tower</option><option>Reactor</option><option>Storage Tank</option><option>Piping</option><option>Boiler</option><option>Furnace</option><option>Other</option></select></label>
    <label>Plant / Unit<input id="eq-unit" placeholder="e.g. LDPE"></label>
    <label>Area<input id="eq-area" placeholder="Area / location"></label>
    <label>Equipment Status *<select id="eq-status"><option>In Service</option><option>Out of Service</option><option>Under Maintenance</option><option>Retired</option></select></label>
  </div></div>
  <div class="form-section"><h3>02 — Service & Process</h3><div class="form-grid">
    <label>Service / Fluid<input id="eq-service" placeholder="Select or define service later"></label>
    <label>Process Description<input id="eq-process" placeholder="Short process description"></label>
    <label>Operating Temperature<input id="eq-op-temp" placeholder="°C"></label>
    <label>Operating Pressure<input id="eq-op-pressure" placeholder="barg"></label>
    <label>Design Temperature<input id="eq-design-temp" placeholder="°C"></label>
    <label>Design Pressure<input id="eq-design-pressure" placeholder="barg"></label>
  </div></div>
  <div class="form-section"><h3>03 — Environment / Process Indicators</h3><div class="form-grid compact">
    <label>H2S<input id="eq-h2s" placeholder="e.g. ppm / wt%"></label><label>CO2<input id="eq-co2" placeholder="e.g. ppm / mol%"></label><label>Chloride<input id="eq-chloride" placeholder="e.g. ppm"></label><label>Amine<input id="eq-amine" placeholder="Yes / No / concentration"></label><label>Water<input id="eq-water" placeholder="Yes / No / concentration"></label><label>Steam<input id="eq-steam" placeholder="Yes / No"></label>
  </div></div>
  <div class="form-section"><h3>04 — Initial Engineering Scope</h3><div class="scope-grid"><div><strong>Components</strong><p>Components will be added after the equipment record is created.</p></div><div><strong>Materials</strong><p>Material master data will be linked to equipment/components.</p></div><div><strong>Damage Mechanisms</strong><p>Potential mechanisms will be assessed using controlled knowledge references.</p></div></div></div>
  <div class="form-actions"><button class="secondary-btn" id="cancel-equipment-2">Cancel</button><button class="primary-btn" id="save-equipment">Create Equipment</button></div>
</div>`;
document.getElementById('cancel-equipment').onclick=()=>render('equipment');document.getElementById('cancel-equipment-2').onclick=()=>render('equipment');
document.getElementById('save-equipment').onclick=()=>{const tag=document.getElementById('eq-tag').value.trim(),type=document.getElementById('eq-type').value;if(!tag||!type){alert('Equipment Tag and Equipment Type are required.');return}const items=getEquipment();if(items.some(x=>x.tag.toLowerCase()===tag.toLowerCase())){alert('This Equipment Tag already exists.');return}items.push({tag,name:document.getElementById('eq-name').value.trim(),type,unit:document.getElementById('eq-unit').value.trim(),area:document.getElementById('eq-area').value.trim(),status:document.getElementById('eq-status').value,service:document.getElementById('eq-service').value.trim(),revision:'01'});saveEquipment(items);render('equipment')};
}
function renderEquipmentList(){const list=document.getElementById('equipment-list');if(!list)return;const search=(document.getElementById('equipment-search')?.value||'').toLowerCase();const type=document.getElementById('equipment-type-filter')?.value||'';const status=document.getElementById('equipment-status-filter')?.value||'';const items=getEquipment().filter(x=>(!search||[x.tag,x.name,x.service,x.unit].join(' ').toLowerCase().includes(search))&&(!type||x.type===type)&&(!status||x.status===status));list.innerHTML=items.length?`<div class="table-wrap"><table class="data-table equipment-table"><thead><tr><th>Tag</th><th>Description</th><th>Type</th><th>Service</th><th>Unit</th><th>Status</th><th>Revision</th></tr></thead><tbody>${items.map(x=>`<tr><td><button class="link-btn" data-eq-tag="${x.tag}">${x.tag}</button></td><td>${x.name||'—'}</td><td>${x.type}</td><td>${x.service||'—'}</td><td>${x.unit||'—'}</td><td><span class="status-badge">${x.status}</span></td><td>Rev. ${x.revision||'01'}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty-state">No equipment records match the current filters.</div>`;document.querySelectorAll('[data-eq-tag]').forEach(b=>b.onclick=()=>equipmentDetail(b.dataset.eqTag));}
function equipmentDetail(tag){const x=getEquipment().find(e=>e.tag===tag);if(!x)return;content.innerHTML=`
<div class="page-panel"><div class="equipment-header"><div><span class="module-code">EQUIPMENT RECORD</span><h2>${x.tag}</h2><p class="placeholder">${x.name||'Equipment'} • Revision ${x.revision||'01'}</p></div><button class="secondary-btn" id="back-equipment">← Equipment List</button></div>
<div class="detail-grid"><div class="detail-card"><span>Equipment Type</span><strong>${x.type}</strong></div><div class="detail-card"><span>Service / Fluid</span><strong>${x.service||'—'}</strong></div><div class="detail-card"><span>Plant / Unit</span><strong>${x.unit||'—'}</strong></div><div class="detail-card"><span>Status</span><strong>${x.status}</strong></div></div>
<div class="section"><h3>Equipment Record</h3><div class="module-list"><div class="module-row"><strong>01 &nbsp; Identification</strong><div>Tag, name, type, hierarchy and status</div></div><div class="module-row"><strong>02 &nbsp; Service & Process</strong><div>Service, operating/design conditions and process indicators</div></div><div class="module-row"><strong>03 &nbsp; Components</strong><div>Subordinate components — ready for implementation</div></div><div class="module-row"><strong>04 &nbsp; Materials</strong><div>Material associations — ready for implementation</div></div><div class="module-row"><strong>05 &nbsp; Damage Mechanisms</strong><div>Potential mechanisms and engineering basis</div></div><div class="module-row"><strong>06 &nbsp; Revision History</strong><div>Current revision: Rev. ${x.revision||'01'} — immutable engineering record model</div></div></div></div>
</div>`;document.getElementById('back-equipment').onclick=()=>render('equipment');}
const originalRender=render;
render=function(page){originalRender(page);if(page==='equipment'){renderEquipmentList();['equipment-search','equipment-type-filter','equipment-status-filter'].forEach(id=>document.getElementById(id)?.addEventListener('input',renderEquipmentList));document.getElementById('add-equipment')?.addEventListener('click',equipmentForm)}};

const initial=window.location.hash.replace('#','')||'dashboard';render(initial);
