const pages={
 dashboard:{title:'Dashboard',html:`<div class="hero"><h2>Caya Asset Integrity Management Platform</h2><p>Controlled engineering workspace based on CSAS Version 1.0. The MVP is being built incrementally around a complete, traceable asset-integrity engineering loop.</p><div class="hero-meta"><span class="chip">CSAS v1.0</span><span class="chip">MVP Phase 1</span><span class="chip">Engineering-first architecture</span></div></div><div class="cards"><div class="card"><div class="label">Equipment</div><div class="value">0</div><div class="sub">Physical assets</div></div><div class="card"><div class="label">RBI Assessments</div><div class="value">0</div><div class="sub">Controlled revisions</div></div><div class="card"><div class="label">Open Triggers</div><div class="value">0</div><div class="sub">Engineering review</div></div><div class="card"><div class="label">Pending Approval</div><div class="value">0</div><div class="sub">Workflow queue</div></div></div><div class="section"><h3>Core Engineering Loop</h3><div class="workflow-line"><span class="workflow-step">Equipment</span><span class="workflow-step">Inspection</span><span class="workflow-step">Corrosion</span><span class="workflow-step">RBI</span><span class="workflow-step">Strategy</span><span class="workflow-step">Review</span><span class="workflow-step">Approval</span></div></div><div class="section"><h3>Platform Modules</h3><div class="module-grid">${moduleCards}</div></div>`},
 equipment:{title:'Equipment',html:`<div class="page-panel equipment-page"><div class="equipment-header"><div><h2>Equipment</h2><p class="placeholder">Primary physical asset records and controlled engineering data.</p></div><button class="primary-btn" id="add-equipment">+ Add Equipment</button></div><div class="equipment-toolbar"><input id="equipment-search" class="search-input" type="search" placeholder="Search equipment by tag, name or service..."><select class="filter-select"><option>All Types</option><option>Pressure Vessel</option><option>Heat Exchanger</option><option>Column / Tower</option></select><select class="filter-select"><option>All Statuses</option><option>In Service</option><option>Out of Service</option></select></div><div id="equipment-list"></div></div>`},
 components:{title:'Components',desc:'Subordinate equipment components such as shell, heads, nozzles, tube bundles and tubesheets. Components are not primary risk units in the current architecture.'},
 services:{title:'Services & Fluids',html:`<div class="page-panel"><div class="equipment-header"><div><h2>Services &amp; Fluids</h2><p class="placeholder">Controlled engineering master data. Service and Fluid are separate objects.</p></div></div><div class="section"><div class="equipment-header"><div><h3>Fluid Database</h3><p class="placeholder">Fluid names are user-defined.</p></div><button class="primary-btn" id="add-fluid">+ Add Fluid</button></div><div class="equipment-toolbar"><input id="fluid-search" class="search-input" placeholder="Search fluid by name..."></div><div id="fluid-list"></div></div><div class="section"><div class="equipment-header"><div><h3>Services</h3><p class="placeholder">Services will reference fluids from the Fluid Database.</p></div><button class="primary-btn" id="add-service">+ Add Service</button></div><div class="empty-state">No service records yet.</div></div></div>`},
 materials:{title:'Materials',desc:'Controlled and versioned material definitions and associations for equipment and components.'},
 damage:{title:'Damage Mechanisms',desc:'Controlled damage-mechanism knowledge. API RP 571 is the principal initial reference; company and practical references are supported.'},
 methods:{title:'Inspection Methods',desc:'Controlled inspection-method definitions, applicability, coverage and effectiveness information used by Inspection and RBI.'},
 references:{title:'Engineering References',desc:'Controlled standards, procedures, specifications, technical papers, manufacturer references and company engineering practices.'},
 inspection:{title:'Inspection',desc:'Inspection requirements, plans, tasks, execution, locations, TML/CML, measurements, NDT results, findings, evidence and achieved effectiveness.'},
 corrosion:{title:'Corrosion',desc:'Corrosion and degradation assessment. Corrosion calculations are owned here; corrosion rate does not independently determine the RBI interval.'},
 rbi:{title:'RBI',desc:'Risk-Based Inspection engineering assessment: PoF, CoF, risk, risk drivers, risk target, required inspection effectiveness, inspection strategy and interval.'},
 ffs:{title:'FFS',desc:'Fitness-for-Service screening and assessment based on controlled API 579-1 / ASME FFS-1 methodologies.'},
 iow:{title:'IOW',desc:'Integrity Operating Windows and operating-event evaluation. IOW boundaries and actual operating observations remain separate controlled objects.'},
 calculation:{title:'Calculation',desc:'Shared controlled calculation infrastructure for RBI, Corrosion, FFS and IOW evaluation.'},
 workflow:{title:'Workflow',desc:'Process execution around engineering assessment, interpretation, decision, technical review, approval, action, verification and closure.'},
 documents:{title:'Documents',desc:'Controlled technical documents, evidence, engineering references and technical knowledge governance.'},
 administration:{title:'Administration',desc:'System governance including users, roles, permissions, organizations, configuration, security and audit.'}
};
const moduleOrder=[['equipment','Equipment'],['components','Components'],['services','Services & Fluids'],['materials','Materials'],['damage','Damage Mechanisms'],['methods','Inspection Methods'],['references','Engineering References'],['inspection','Inspection'],['corrosion','Corrosion'],['rbi','RBI'],['ffs','FFS'],['iow','IOW'],['calculation','Calculation'],['workflow','Workflow'],['documents','Documents'],['administration','Administration']];
const moduleCards=moduleOrder.map(([id,name])=>`<div class="module" data-page="${id}"><span class="module-code">${id.toUpperCase()}</span><strong>${name}</strong></div>`).join('');
const content=document.getElementById('page-content');const title=document.getElementById('page-title');
const defaultEquipment=[{tag:'42-V-30001',name:'Quench Water Tower',type:'Column / Tower',service:'Quench Water',unit:'LDPE',status:'In Service',revision:'01'}];
function getFluids(){const d=[{id:'FLD-001',name:'Water',description:'Generic water fluid definition',status:'Active',revision:'01'},{id:'FLD-002',name:'Ethylene',description:'Generic ethylene fluid definition',status:'Active',revision:'01'},{id:'FLD-003',name:'Wash Oil',description:'Generic wash oil fluid definition',status:'Active',revision:'01'}];try{const x=JSON.parse(localStorage.getItem('caya-fluids'));return Array.isArray(x)&&x.length?x:d}catch(e){return d}}
function saveFluids(x){localStorage.setItem('caya-fluids',JSON.stringify(x))}
function renderFluids(){const q=(document.getElementById('fluid-search')?.value||'').toLowerCase();const rows=getFluids().filter(x=>x.name.toLowerCase().includes(q));const el=document.getElementById('fluid-list');if(!el)return;el.innerHTML=rows.length?`<table class="equipment-table"><thead><tr><th>Fluid ID</th><th>Fluid Name</th><th>Description</th><th>Status</th><th>Revision</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.id}</td><td><strong>${x.name}</strong></td><td>${x.description||'—'}</td><td>${x.status}</td><td>${x.revision}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">No fluids found.</div>'}
function servicesPage(){document.getElementById('add-fluid').onclick=()=>{const name=prompt('Fluid Name *');if(!name||!name.trim())return;const fluids=getFluids();if(fluids.some(x=>x.name.toLowerCase()===name.trim().toLowerCase())){alert('This fluid already exists.');return}const n=fluids.length+1;fluids.push({id:'FLD-'+String(n).padStart(3,'0'),name:name.trim(),description:'',status:'Active',revision:'01'});saveFluids(fluids);renderFluids()};document.getElementById('fluid-search').oninput=renderFluids;document.getElementById('add-service').onclick=()=>alert('Service creation will be implemented after the Fluid Database is reviewed.');renderFluids()}
function equipmentList(){document.getElementById('add-equipment').onclick=()=>alert('Add Equipment is working.');document.getElementById('equipment-list').innerHTML='<div class="empty-state">42-V-30001 — Quench Water Tower — Column / Tower — Quench Water<br><br><a class="link-btn" href="equipment.html">Open Equipment</a></div>'}
function render(page){const p=pages[page]||pages.dashboard;title.textContent=p.title;content.innerHTML=p.html||`<div class="page-panel"><h2>${p.title}</h2><p class="placeholder">${p.desc}</p><div class="empty-state">No records yet. This module is structurally defined and ready for implementation.</div></div>`;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>render(x.dataset.page));if(page==='equipment')equipmentList();if(page==='services')servicesPage();window.location.hash=page}
document.addEventListener('DOMContentLoaded',()=>render(window.location.hash.replace('#','')||'dashboard'));